/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Insets;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.border.EmptyBorder;



/**
 *
 * @author STALIN
 */
public class DIBUJOS extends javax.swing.JFrame {

    
   
    
    public DIBUJOS() {
        initComponents();
        
        //ImageIcon fot = new ImageIcon("src/Imagenes/retroceder.jpg");
        //Icon icono = new ImageIcon(fot.getImage().getScaledInstance(tc.getWidth(),tc.getHeight(), Image.SCALE_SMOOTH));
        //tc.setIcon(icono);
        //tc.setBackground(Color.green);
        //this.pack();
        //dibujarB(tc,"src/Imagenes/retroceder.jpg",Color.green);
        dibujarBoton(tc,"src/Imagenes/verdeC.jpg","src/Imagenes/verdeO.jpg");
        
        //this.setResizable(false);
        
        //setDefaultCloseOperation(DIBUJOS.EXIT_ON_CLOSE);
        //setBounds(100, 100, 450, 300);   
        //Imagen im = new Imagen();
        //this.add(im, BorderLayout.CENTER);
        //this.setVisible(true);
        //this.pack();
        
        //im.setBorder(new EmptyBorder(5, 5, 5, 5));
        //im.setLayout(new BorderLayout(0, 0));
        //bb.setOpaque(false);
        //setContentPane(im);
        
    }
    public void dibujarB( JButton b , String d, Color g) {
 
        ImageIcon fot = new ImageIcon(d);
        Icon icono = new ImageIcon(fot.getImage().getScaledInstance(b.getWidth(),b.getHeight(), Image.SCALE_SMOOTH));
        b.setIcon(icono);
        b.setBackground(g);
        this.pack();
  }
    
  public void dibujarBoton( JButton b , String d, String e) {
 
        ImageIcon fot = new ImageIcon(d);
        Icon icono = new ImageIcon(fot.getImage().getScaledInstance(b.getWidth(),b.getHeight(), Image.SCALE_SMOOTH));
        b.setIcon(icono);
        b.setRolloverIcon(new ImageIcon(e));
        b.setBorderPainted(false);
        this.pack();
  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tc = new javax.swing.JButton();
        hb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcActionPerformed(evt);
            }
        });
        getContentPane().add(tc, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 120, 80));
        getContentPane().add(hb, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcActionPerformed
        System.out.println("Haz aplastado el boton");
    }//GEN-LAST:event_tcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DIBUJOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DIBUJOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DIBUJOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DIBUJOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DIBUJOS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hb;
    private javax.swing.JButton tc;
    // End of variables declaration//GEN-END:variables
}
