package proyecto;
import java.awt.Color;
import java.awt.Image;
import java.io.Serializable;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author AdminPC
 */
public class FrmAdministrador extends javax.swing.JFrame implements Serializable {
    ArrayList<ClsProfesor> profesores = new ArrayList<>();
    ArrayList<Object> maestros = new ArrayList<>();
    ArrayList<ClsAdministrador> administradores = new ArrayList<>();
    
    ClsControlador control = new ClsControlador();
    int cont = 0;
    int a = 0;
    int b = 0;
    String nombreP,apellidoP,tituloP;
    long cedulaP;
    int seleccion = 0;
    int puntajeS = 0;
   public FrmAdministrador() {
        initComponents();
        this.setTitle("MENU DEL ADMINISTRADOR");
        this.setResizable(false);
        BtnGuardar.setBackground(Color.green);
        BtnRegresarA.setBackground(Color.red);
        BtnCrearA.setBackground(Color.cyan);       
        btnEliminarA.setBackground(Color.blue);
        BtnListar.setBackground(Color.yellow);
        ClsControlador control = new ClsControlador();
        maestros = control.extraer("profesores.dat");
        if (maestros.size()>0){
        ClsProfesor ultima=(ClsProfesor)maestros.get(maestros.size()-1);
        cont=ultima.getId()+1;
        }
        ClsAdministrador adm1 = new ClsAdministrador (0,"Stalin", "Maza",1725452609);
        ClsAdministrador adm2 =  new ClsAdministrador (1,"Mishel","Centeno",1224364860);
        administradores.add(adm1);
        administradores.add(adm2);
        txtNombreA.setEnabled(false);
        txtApellidoA.setEnabled(false);
        txtTituloA.setEnabled(false);
        txtCedulaA.setEnabled(false);
        ImageIcon imagen = new ImageIcon("src/Imagenes/admi.jpg");
        Icon icono1 = new ImageIcon(imagen.getImage().getScaledInstance(lblnada.getWidth(),lblnada.getHeight(),Image.SCALE_DEFAULT));
        lblnada.setIcon(icono1);
        this.pack();
        llenarComboCarga();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEliminarA = new javax.swing.JButton();
        btnModificarA = new javax.swing.JButton();
        BtnCrearA = new javax.swing.JButton();
        BtnListar = new javax.swing.JButton();
        lblnombre = new javax.swing.JLabel();
        txtNombreA = new javax.swing.JTextField();
        lblapellido = new javax.swing.JLabel();
        txtApellidoA = new javax.swing.JTextField();
        lbltitulo = new javax.swing.JLabel();
        txtTituloA = new javax.swing.JTextField();
        lblcedula = new javax.swing.JLabel();
        txtCedulaA = new javax.swing.JTextField();
        BtnGuardar = new javax.swing.JButton();
        BtnRegresarA = new javax.swing.JButton();
        cmbL = new javax.swing.JComboBox<>();
        btnCM = new javax.swing.JButton();
        lblnada = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEliminarA.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEliminarA.setText("ELIMINAR");
        btnEliminarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarAActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminarA, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, -1, 40));

        btnModificarA.setBackground(new java.awt.Color(255, 204, 204));
        btnModificarA.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnModificarA.setText("MODIFICAR");
        btnModificarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarAActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificarA, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, -1, 30));

        BtnCrearA.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnCrearA.setText("NUEVO");
        BtnCrearA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCrearAActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCrearA, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 90, 30));

        BtnListar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnListar.setText("LISTAR");
        BtnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnListarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 90, 40));

        lblnombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblnombre.setText("NOMBRES :");
        getContentPane().add(lblnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 83, -1));
        getContentPane().add(txtNombreA, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 177, -1));

        lblapellido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblapellido.setText("APELLIDOS :");
        getContentPane().add(lblapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 100, -1));
        getContentPane().add(txtApellidoA, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 177, -1));

        lbltitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbltitulo.setText("TITULO :");
        getContentPane().add(lbltitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 83, -1));
        getContentPane().add(txtTituloA, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 177, -1));

        lblcedula.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblcedula.setText("CEDULA :");
        getContentPane().add(lblcedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 83, -1));
        getContentPane().add(txtCedulaA, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 177, -1));

        BtnGuardar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnGuardar.setText("GUARDAR");
        BtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, 40));

        BtnRegresarA.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnRegresarA.setText("REGRESAR");
        BtnRegresarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegresarAActionPerformed(evt);
            }
        });
        getContentPane().add(BtnRegresarA, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 100, 40));

        cmbL.setBackground(new java.awt.Color(51, 255, 51));
        cmbL.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cmbL.setForeground(new java.awt.Color(0, 0, 204));
        cmbL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbLActionPerformed(evt);
            }
        });
        getContentPane().add(cmbL, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, 30));

        btnCM.setBackground(new java.awt.Color(255, 204, 204));
        btnCM.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCM.setText("CONFIRMAR");
        btnCM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCMActionPerformed(evt);
            }
        });
        getContentPane().add(btnCM, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, -1, 30));

        lblnada.setBackground(new java.awt.Color(51, 204, 255));
        lblnada.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(lblnada, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRegresarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegresarAActionPerformed
        FrmLogin log1 = new FrmLogin();
        log1.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_BtnRegresarAActionPerformed

    private void BtnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnListarActionPerformed

        FrmListar lista1 = new FrmListar();
        lista1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnListarActionPerformed

    private void BtnCrearAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCrearAActionPerformed
        habilitar1();        
    }//GEN-LAST:event_BtnCrearAActionPerformed

    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed
       validarCedula prueba = new validarCedula();
        if ( prueba.getValidacion( txtCedulaA.getText()) == true ) {
        JOptionPane.showMessageDialog(null,"Cedula Valida");
       ClsProfesor profesor1 = new ClsProfesor(cont,txtNombreA.getText(),txtApellidoA.getText(),Long.parseLong(txtCedulaA.getText()),txtTituloA.getText(),0);
       ClsProfesor leer = new ClsProfesor();
       cont++; 
       System.out.println("Cont" + cont);
       String Dato [] = new String [3];       
       maestros.add(profesor1);       
       control.insertar("profesores.dat", maestros);       
       maestros = control.extraer("profesores.dat");
       a = maestros.size();
       System.out.println("Tamaño" + a);
       for (int i = 0; i < maestros.size(); i++) {
           System.out.println(maestros.get(i));
        }
        for (int i = 0; i < maestros.size(); i++) {
           leer = (ClsProfesor) maestros.get(i);
           System.out.println(leer.getApellido());
        }
        Dato[0] = String.valueOf(cont);
        Dato[1] = txtNombreA.getText();
        Dato[2] = String.valueOf((23));
        cont++;
        Listar lista = new Listar();
        lista.modelo.addRow(Dato);
        lista.setVisible(true);
        } else { JOptionPane.showMessageDialog(null,"Ingrese una Cedula Valida"); }
    }//GEN-LAST:event_BtnGuardarActionPerformed

     public void llenarComboCarga(){
    //regper= personas.size();
         if(maestros.size() > 0){
                ClsControlador control = new ClsControlador();
                maestros = control.extraer("profesores.dat");
                cmbL.setModel(new javax.swing.DefaultComboBoxModel(maestros.toArray()));
                }
        }
    private void btnModificarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarAActionPerformed
        habilitar2();
    }//GEN-LAST:event_btnModificarAActionPerformed

    private void btnEliminarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarAActionPerformed
     maestros.remove(seleccion);
     control.insertar("profesores.dat", maestros);
     llenarComboCarga();
    }//GEN-LAST:event_btnEliminarAActionPerformed

    private void cmbLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbLActionPerformed
        seleccion = cmbL.getSelectedIndex();
        ClsProfesor obtener = new ClsProfesor();
        for (int i = 0; i< maestros.size(); i++ ) {
                    obtener = (ClsProfesor) maestros.get(i);
                     if ( i == seleccion ) {
                       txtNombreA.setText(obtener.getNombre());
                       txtApellidoA.setText(obtener.getApellido());
                       txtTituloA.setText(obtener.getTitulo());
                       txtCedulaA.setText(String.valueOf(obtener.getCedula()));
                       puntajeS = obtener.getPuntaje();
                       i = maestros.size();
                                                    }             
                    } 
        System.out.println("Id Seleccionado:" + seleccion );
    }//GEN-LAST:event_cmbLActionPerformed

    private void btnCMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCMActionPerformed
      int posicion = 0;
      maestros = control.extraer("profesores.dat");
      nombreP = this.txtNombreA.getText();
      apellidoP = this.txtApellidoA.getText();
      cedulaP = Long.parseLong(this.txtCedulaA.getText());
      tituloP = this.txtTituloA.getText();
      ClsProfesor leer = new ClsProfesor(seleccion,nombreP,apellidoP,cedulaP,tituloP,puntajeS);
      System.out.println("ID: " + seleccion);          
      maestros.remove(seleccion);
      maestros.add(leer);
      control.insertar("profesores.dat", maestros);
        llenarComboCarga();
        System.out.println("Haz modificado");
    }//GEN-LAST:event_btnCMActionPerformed

    public void habilitar1() {
        txtNombreA.setEnabled(true);
        txtApellidoA.setEnabled(true);
        txtTituloA.setEnabled(true);
        txtCedulaA.setEnabled(true);
    }    
    public void habilitar2() {
        txtTituloA.setEnabled(true);
        txtCedulaA.setEnabled(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCrearA;
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JButton BtnListar;
    private javax.swing.JButton BtnRegresarA;
    private javax.swing.JButton btnCM;
    private javax.swing.JButton btnEliminarA;
    private javax.swing.JButton btnModificarA;
    private javax.swing.JComboBox<String> cmbL;
    private javax.swing.JLabel lblapellido;
    private javax.swing.JLabel lblcedula;
    private javax.swing.JLabel lblnada;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JLabel lbltitulo;
    public javax.swing.JTextField txtApellidoA;
    public static javax.swing.JTextField txtCedulaA;
    public static javax.swing.JTextField txtNombreA;
    public static javax.swing.JTextField txtTituloA;
    // End of variables declaration//GEN-END:variables
}
